spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost:5432/rpg}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:data-postgres.sql
      mode: always